dist: trusty

language: node_js
node_js:
  - "8"
  - node

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
    - ~/.cache

notifications:
  email: false

before_install:
  - npm i -g yarn

install:
  - yarn install --frozen-lockfile

script:
  - yarn lint
  - yarn test

jobs:
  include:
    - stage: default
      if: branch = master AND type = push
      node_js: node
      script:
        - yarn build
